# Generated by Django 2.2.3 on 2019-07-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourleader', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('day', models.IntegerField(default=True)),
                ('month', models.IntegerField(default=True)),
            ],
        ),
    ]
