# Generated by Django 2.2.3 on 2019-07-28 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('havale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthday', models.IntegerField(default=True)),
                ('birthmonth', models.IntegerField(default=True)),
                ('birthyear', models.IntegerField(default=True)),
                ('passport', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('ischild', models.BooleanField(default=True)),
                ('touri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='havale.tour')),
            ],
        ),
    ]
