# Generated by Django 2.2.3 on 2019-07-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havale', '0003_auto_20190728_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='phone',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
