# Generated by Django 2.2.3 on 2019-07-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('ishow', models.IntegerField(max_length=30)),
            ],
        ),
    ]
