# Generated by Django 2.2.3 on 2019-07-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='pricecard',
        ),
    ]
