# Generated by Django 2.2.3 on 2019-07-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0004_auto_20190716_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecard',
            name='ishow',
            field=models.BooleanField(default=False),
        ),
    ]
