# Generated by Django 2.2.3 on 2019-07-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchange', '0005_auto_20190728_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecard',
            name='ishow',
            field=models.BooleanField(default=True),
        ),
    ]
